import asyncio
from typing import Protocol, Awaitable
from .models import RecoveryTicket, ResourceKey

class RecoveryControl(Protocol):
    def begin_recovery(self, keys: tuple[str, ...]) -> RecoveryTicket: ...
    async def wait_recovery(self, ticket: RecoveryTicket) -> None: ...
    def recovery_ready(self) -> bool: ...
    async def prepare_shutdown(self) -> None: ...
