"""Audio HAL protocols."""

from typing import AsyncIterator, Protocol, runtime_checkable


@runtime_checkable
class AudioInput(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    def frames(self) -> AsyncIterator[bytes]: ...


@runtime_checkable
class AudioOutput(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def play(self, pcm: AsyncIterator[bytes]) -> None: ...
