"""Display HAL protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class DisplayDevice(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    def clear(self) -> None: ...
    def write_pixels(self, buf: bytes) -> None: ...
    def show(self) -> None: ...
    def size(self) -> tuple[int, int]: ...
